### ISSUE TITLE
ClassNotFoundException for AppServiceMSICredentials 

### ISSUE THREAD

**Issue by ttworek** [Microsoft/azure-spring-boot#556]
## Environment
- Spring boot starter:
  
  - key vault spring boot starter
  
- OS Type: Linux/MacOS
- Java version: 
  - 1.8
  

## Summary
I am trying to setup Azure KeyVault using a Managed Identity.  I am able to get it to work if I provide the client-id and client-key in the application.properties file, but when attempting to use a managed identiy, I get the following ClassNotFoundException for AppServiceMSICredentials on startup:

```
2019-02-02T21:21:33.410331212Z Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
2019-02-02T21:21:43.706665780Z AI: INFO 02-02-2019 21:21, 1: Configuration file has been successfully found as resource
2019-02-02T21:21:53.485474712Z AI: ERROR 02-02-2019 21:21, 1: Failed to create com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule, com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule
2019-02-02T21:21:53.640633371Z AI: INFO 02-02-2019 21:21, 1: Configuration file has been successfully found as resource
2019-02-02T21:21:54.231503197Z AI: ERROR 02-02-2019 21:21, 1: Failed to create com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule, com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule
2019-02-02T21:21:54.495228635Z 21:21:54.464 [main] DEBUG org.springframework.boot.context.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: [jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-web-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-logging-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/logback-core-1.2.3.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/log4j-to-slf4j-2.11.1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/log4j-api-2.11.1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jul-to-slf4j-1.7.25.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/javax.annotation-api-1.3.2.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/snakeyaml-1.23.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-json-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jackson-databind-2.9.8.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-tomcat-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/tomcat-embed-core-9.0.14.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/tomcat-embed-el-9.0.14.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/tomcat-embed-websocket-9.0.14.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/hibernate-validator-6.0.14.Final.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/validation-api-2.0.1.Final.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jboss-logging-3.3.2.Final.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/classmate-1.4.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-web-5.1.4.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-webmvc-5.1.4.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-actuator-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-actuator-autoconfigure-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-actuator-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/micrometer-core-1.1.2.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/HdrHistogram-2.1.9.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/LatencyUtils-2.0.3.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-thymeleaf-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/thymeleaf-spring5-3.0.11.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/thymeleaf-3.0.11.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/attoparser-2.0.5.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/unbescape-1.1.6.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/slf4j-api-1.7.25.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/thymeleaf-extras-java8time-3.0.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-security-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-aop-5.1.4.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-security-config-5.1.3.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-security-core-5.1.3.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-security-web-5.1.3.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-session-1.3.5.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/commons-logging-1.2.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/azure-spring-boot-starter-2.1.2.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-starter-validation-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/azure-spring-boot-2.1.2.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-data-cosmosdb-2.1.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-core-5.1.4.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-jcl-5.1.4.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-beans-5.1.4.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-context-5.1.4.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-tx-5.1.4.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-data-commons-2.1.4.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-expression-5.1.4.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/azure-documentdb-1.16.2.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/java-uuid-generator-3.1.4.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/json-20140107.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/httpclient-4.5.6.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/httpcore-4.4.10.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/joda-time-2.10.1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jackson-module-parameter-names-2.9.8.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jackson-core-2.9.8.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jackson-datatype-jdk8-2.9.8.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jackson-datatype-jsr310-2.9.8.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jackson-annotations-2.9.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/applicationinsights-core-2.0.1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/annotation-detector-3.0.5.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/guava-20.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/gson-2.8.5.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/javatuples-1.2.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/azure-keyvault-secrets-spring-boot-starter-2.1.2.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/azure-keyvault-1.0.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/azure-client-runtime-1.0.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/client-runtime-1.0.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/retrofit-2.1.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/okhttp-urlconnection-3.3.1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/converter-jackson-2.1.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jackson-datatype-joda-2.9.8.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/rxjava-1.3.8.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/adapter-rxjava-2.1.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/azure-keyvault-webkey-1.0.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/adal4j-1.6.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/oauth2-oidc-sdk-5.24.1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/mail-1.4.7.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/activation-1.1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jcip-annotations-1.0-1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/commons-collections4-4.1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/lang-tag-1.4.4.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/nimbus-jose-jwt-6.8.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/commons-codec-1.11.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/commons-io-2.3.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/mvc-auth-commons-1.0.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/javax.servlet-api-4.0.1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/bcprov-jdk15on-1.57.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/commons-lang3-3.8.1.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/auth0-1.1.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/okhttp-3.7.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/okio-1.12.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/logging-interceptor-3.7.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/java-jwt-3.2.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/jwks-rsa-0.2.0.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/lombok-1.18.4.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-autoconfigure-2.1.2.RELEASE.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/json-smart-2.3.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/accessors-smart-1.2.jar!/, jar:file:/home/site/wwwroot/openhoa-webapp-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/asm-5.0.4.jar!/]
2019-02-02T21:21:54.524135615Z 21:21:54.512 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
2019-02-02T21:21:54.524171816Z java.lang.NoClassDefFoundError: com/microsoft/azure/credentials/AppServiceMSICredentials
2019-02-02T21:21:54.524177617Z 	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.getCredentials(KeyVaultEnvironmentPostProcessorHelper.java:85)
2019-02-02T21:21:54.524183817Z 	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource(KeyVaultEnvironmentPostProcessorHelper.java:49)
2019-02-02T21:21:54.524188617Z 	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessor.postProcessEnvironment(KeyVaultEnvironmentPostProcessor.java:26)
2019-02-02T21:21:54.524193617Z 	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:177)
2019-02-02T21:21:54.524198317Z 	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:163)
2019-02-02T21:21:54.524202817Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
2019-02-02T21:21:54.524207418Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
2019-02-02T21:21:54.524211918Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
2019-02-02T21:21:54.524216918Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
2019-02-02T21:21:54.524221818Z 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
2019-02-02T21:21:54.524226418Z 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
2019-02-02T21:21:54.524230918Z 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
2019-02-02T21:21:54.524235419Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
2019-02-02T21:21:54.524254519Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
2019-02-02T21:21:54.524259719Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
2019-02-02T21:21:54.524265320Z 	at net.openhoa.webapp.Application.main(Application.java:12)
2019-02-02T21:21:54.524270120Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2019-02-02T21:21:54.524274520Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2019-02-02T21:21:54.524278920Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2019-02-02T21:21:54.524283420Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2019-02-02T21:21:54.524287820Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2019-02-02T21:21:54.524292221Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2019-02-02T21:21:54.524296621Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2019-02-02T21:21:54.524301021Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
2019-02-02T21:21:54.524305421Z Caused by: java.lang.ClassNotFoundException: com.microsoft.azure.credentials.AppServiceMSICredentials
2019-02-02T21:21:54.524309921Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
2019-02-02T21:21:54.524314321Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2019-02-02T21:21:54.524318721Z 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
2019-02-02T21:21:54.524323322Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2019-02-02T21:21:54.524327622Z 	... 24 common frames omitted
2019-02-02T21:21:55.253900149Z Initialization script exited with code 1
2019-02-02 21:21:56.157 ERROR - Container openhoa-webapp_0 for site openhoa-webapp has exited, failing site start
```
Using the following dependency:
```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
            <version>2.1.2</version>
        </dependency>
```

And the following in my application.properties:

```
azure.keyvault.uri=https://my-keyvault.vault.azure.net/
azure.keyvault.enabled=true
```

## Reproduce steps
Follow basic tutorial here:
https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot-starters/azure-keyvault-secrets-spring-boot-starter/README.md

## Expected Results
The servic launches and my webapp hosted in Azure is able to access my secretes in the keyvault using a Managed identity

## Actual Results
ClassNotFoundException for AppServiceMSICredentials on startup

**Comment by TroubleConsultant** [comment]
I have the same issue.

**Comment by ttworek** [comment]
Great! Thanks so much, it worked.

Unblocks me for now, but yea, the proper solution should be looked into or mentioned in the readme/guide.  Wasted quite a bit of time on this.

**Comment by TroubleConsultant** [comment]
I don't think you should close the issue personally. The dependencies in the POM aren't right if they don't include the azure core project.

**Comment by ttworek** [comment]
Agreed, reopening

**Comment by xscript** [comment]
Thanks @ttworek @TroubleConsultant for reporting this issue and providing work around!
We will look into this and provide a update soon.

**Comment by fox918** [comment]
```
Spring: 2.0
Ressource: Container Ressource Group 
Java: 10
```

I have the same Issue as desbribed above, however for me the Exception is: 
`ClassNotFoundException: MSICredentials`

As desribed above, if I provide a Service Principal (RBSS) with a secret, everything works.
If I however deploy using only the Key-Vault URI and a Managed Identity, then the `ClassNotFoundException` occurs.
This is also true if I addionally provide the **client-id** of the Managed Identity

Used dependency:
- compile('com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:2.0.11')
Included dependency as per workaround:
- compile(group: 'com.microsoft.azure', name:'azure', version:'1.19.0')

I have further tried deploying using the fixes introduced above with a self-built
_azure-keyvault-secrets-spring-boot-starter:2.0.12-SNAPSHOT_
still the error reproduces.

Steps to reproduce:
1. Deploy Key vault and a new Identity to a ressource group 
2. Deploy Container-Ressource using:
`az container create -g portal-snapshot -n portal-snapshot-api --image <path> --assign-identity <identity>`
3. Docker image fails to correctly start Spring because of `ClassNotFoundException: MSICredentials`

application.properties:
```
azure:
  keyvault:
    enabled: true
    uri: "https://vault-snapshot.vault.azure.net/"
    token-acquiring-timeout-seconds: 120
```
Error-Log:
```
AI: INFO 18-02-2019 09:16, 1: Configuration file has been successfully found as resource
AI: ERROR 18-02-2019 09:16, 1: Failed to create com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule, com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule
AI: INFO 18-02-2019 09:16, 1: Configuration file has been successfully found as resource
AI: ERROR 18-02-2019 09:16, 1: Failed to create com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule, com.microsoft.applicationinsights.web.internal.perfcounter.WebPerformanceCounterModule
[ERROR] SpringApplication - Application run failed <java.lang.NoClassDefFoundError: com/microsoft/azure/credentials/MSICredentials>java.lang.NoClassDefFoundError: com/microsoft/azure/credentials/MSICredentials
	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.getCredentials(KeyVaultEnvironmentPostProcessorHelper.java:114)
	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource(KeyVaultEnvironmentPostProcessorHelper.java:49)
	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessor.postProcessEnvironment(KeyVaultEnvironmentPostProcessor.java:26)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:183)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
	at com.medartis.portal.PortalApplication.main(PortalApplication.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ClassNotFoundException: com.microsoft.azure.credentials.MSICredentials
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 24 more
```

**Comment by fox918** [comment]
Just as an addendum, deployment fails using either a self-created Managed Identity but also when usign a system assigned Managed Identity

**Comment by sophiaso** [comment]
@fox918 Sounds weird to me, you mentioned that you have built a new snapshot version, from the failure stacktrace log it shows:
```
[ERROR] SpringApplication - Application run failed <java.lang.NoClassDefFoundError: com/microsoft/azure/credentials/MSICredentials>java.lang.NoClassDefFoundError: com/microsoft/azure/credentials/MSICredentials
	at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.getCredentials(KeyVaultEnvironmentPostProcessorHelper.java:114)
```

But in the master branch line 114, we have changed the Java class to [AzureKeyVaultMSICredential](https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot/src/main/java/com/microsoft/azure/keyvault/spring/KeyVaultEnvironmentPostProcessorHelper.java#L114), could you try pull the latest master branch and build again?

**Comment by fox918** [comment]
Yes I will try doing this.
At the moment I use the key storage while providing a _client-id_ and a _client-key_. 
Somehting curious I noticed:  
I do see the above stacktrace when deploying to the Azure Container Group but I do not see the stacktrace when running the application locally. Furthermore the application will run and retrieve secrets even when the stacktrace is seen.

**Comment by sophiaso** [comment]
If you are running application locally, I suppose you have configured the `client-id` and `client-secret`, the stacktrace should not show up as you are not using MSI. 

`Furthermore the application will run and retrieve secrets even when the stacktrace is seen.` Basically the application should not work if you have seen the stacktrace.

**Comment by fox918** [comment]
Ok, I have to admit that the produced error and stacktrace was my fault.
This was primarily the case because we didn't use Spring 2.0.3
I should have better isolated the fault from our main code.

My resolution:
- Update Spring Boot to >= 2.0.3 (before it was 2.0.0)
- Use Azure Spring Keyvault Starters Version 2.0.11
- Provide `client-id` and `client-key` of a role based service principal
(as [noted](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-managed-identity) by Microsoft, we cannot use managed identities in production because we eventually deploy to a vlan)

Then the above fault does not occur anymore. The spring application continued afterwards because
of some issue we had in our containerization pipeline.

**Comment by sophiaso** [comment]
@fox918 Good to know, thanks for the details.

**Comment by sophiaso** [comment]
Hi @ttworek, @TroubleConsultant, we have released a new version [2.1.4 starter](https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault-secrets-spring-boot-starter/2.1.4), could you try whether it fixes your issue? Thanks.

**Comment by TroubleConsultant** [comment]
New version works without manually including the missing dependency. SUCCESS

**Comment by sophiaso** [comment]
Thanks @TroubleConsultant for the confirm, close this issue then.

**Comment by cosolg** [comment]
Hi, I am still facing the same issue even with 2.1.4  starter. Can you please assist?

**Comment by sophiaso** [comment]
@cosolg could you provide a simplest project which reproduces your issue?
