### ISSUE TITLE
Stop overriding dependency management provided by Spring Boot in azure-spring-boot-parent

### ISSUE THREAD

**Issue by snicoll** [microsoft/azure-spring-boot#757]
There are a number of dependency management decisions in the parent of this project that looks wrong to me. The purpose of this project is to integrate Azure with Spring Boot. A Spring Boot project is very much likely to use its dependency management and, as a result, versions for a number of dependencies will be set to a well-defined version, regardless of what individual project in the dependency tree defines.

The main arguments for this is to make sure that:

A. We don't have mixed versions of the same project (i.e. `spring-core` version A and `spring-beans` version B)
B. We don't get incompatible/unsupported versions on the classpath

This project should build with those decisions as well, any attempt to deviate is calling for trouble as this project would build against local decisions and fail in a vanilla Spring Boot app. 

Based on this analysis, please stop overriding the following:

Spring Framework: https://github.com/microsoft/azure-spring-boot/blob/a22d547dc984c49fe7ebca8e847a698cfd7d35d5/azure-spring-boot-parent/pom.xml#L121-L126

Micrometer (might be a leftover): https://github.com/microsoft/azure-spring-boot/blob/a22d547dc984c49fe7ebca8e847a698cfd7d35d5/azure-spring-boot-parent/pom.xml#L36

Hibernate validator: https://github.com/microsoft/azure-spring-boot/blob/a22d547dc984c49fe7ebca8e847a698cfd7d35d5/azure-spring-boot-parent/pom.xml#L115-L119

It's not a problem to override Mockito as it only affects your tests but FYI, Spring Boot provides dependency management for that as well. 

The list of versions that are managed [is available in the Appendix](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html#appendix-dependency-versions) of each release.

**Comment by saragluna** [comment]
Thanks for your update and the mentioned will be taken care of.

**Comment by 2020-abhilash** [comment]
I spend a couple of days struggling with my spring boot project just to find out that the application insights starter project is messing with my own versions defined in the projects. Fixing this issue will immensely help many and save a lot of time.

**Comment by snicoll** [comment]
@saragluna do you have an estimate ETA for this fix please?

**Comment by saragluna** [comment]
We are planning a release this week, including 2.1.x and 2.2.x, and this fix will be included.

**Comment by anumalasri** [comment]
Are we going to address this issue #794, as part of release ?

**Comment by saragluna** [comment]
Due to our schedule changes there will be some delay of our next release. Sorry for the inconvenience.

**Comment by neuqlz** [comment]
The overwrite problem has been fixed in latest SNAPSHOT version.

**Comment by snicoll** [comment]
@neuqlz I don't understand how that has been fixed the way the issue is described. I've created https://github.com/Azure/azure-sdk-for-java/issues/13413 to follow-up in the new repo.

**Comment by chenrujun** [comment]
Hi, @snicoll .

> Based on this analysis, please stop overriding the following:

In current repo, the `overriding` content has already been removed.
Refs: https://github.com/microsoft/azure-spring-boot/blob/2.3.x/azure-spring-boot-parent/pom.xml

**Comment by snicoll** [comment]
Hi @chenrujun, thank you for the link. Alright, that looks like it did, indeed. Adding a link to the commit here would have been useful as it didn't occur to me I had to look in a branch.

The problem is back on the new location as far as I can see though. Let's folow-up there.
